"""add coupon body_html and new banner slots

Revision ID: 0177613caa7e
Revises: bb7374e9e54e
Create Date: 2026-04-10 13:15:54.181236

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0177613caa7e'
down_revision = 'bb7374e9e54e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('coupons', schema=None) as batch_op:
        batch_op.add_column(sa.Column('body_html', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('coupons', schema=None) as batch_op:
        batch_op.drop_column('body_html')

    # ### end Alembic commands ###
