"""add site_settings table

Revision ID: 27416c5a36c7
Revises: ec071f096420
Create Date: 2026-04-15 15:41:25.287577

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '27416c5a36c7'
down_revision = 'ec071f096420'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('site_settings',
    sa.Column('key', sa.Text(), nullable=False),
    sa.Column('value', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('site_settings')
    # ### end Alembic commands ###
