"""add game outcomes table and refactor game

Revision ID: 7564564ee7d9
Revises: a7933dd2b39f
Create Date: 2026-04-10 21:02:26.950738

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7564564ee7d9'
down_revision = 'a7933dd2b39f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('game_outcomes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('label', sa.Text(), nullable=False),
    sa.Column('points', sa.Integer(), nullable=False),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.Column('color', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('game_id', 'position', name='uq_game_outcome_position')
    )
    with op.batch_alter_table('game_play_logs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('outcome_position', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('result_label', sa.Text(), nullable=True))
        batch_op.drop_column('result')

    with op.batch_alter_table('games', schema=None) as batch_op:
        batch_op.drop_column('points_on_lose')
        batch_op.drop_column('win_rate')
        batch_op.drop_column('points_on_win_max')
        batch_op.drop_column('points_on_win_min')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('games', schema=None) as batch_op:
        batch_op.add_column(sa.Column('points_on_win_min', sa.INTEGER(), nullable=False))
        batch_op.add_column(sa.Column('points_on_win_max', sa.INTEGER(), nullable=False))
        batch_op.add_column(sa.Column('win_rate', sa.FLOAT(), nullable=False))
        batch_op.add_column(sa.Column('points_on_lose', sa.INTEGER(), nullable=False))

    with op.batch_alter_table('game_play_logs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('result', sa.TEXT(), nullable=False))
        batch_op.drop_column('result_label')
        batch_op.drop_column('outcome_position')

    op.drop_table('game_outcomes')
    # ### end Alembic commands ###
