"""add content_html to site_assets

Revision ID: a7933dd2b39f
Revises: 0177613caa7e
Create Date: 2026-04-10 13:33:44.077010

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a7933dd2b39f'
down_revision = '0177613caa7e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('site_assets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('content_html', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('site_assets', schema=None) as batch_op:
        batch_op.drop_column('content_html')

    # ### end Alembic commands ###
