"""add home_banners table

Revision ID: ec071f096420
Revises: 7564564ee7d9
Create Date: 2026-04-15 15:01:11.597376

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ec071f096420'
down_revision = '7564564ee7d9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('home_banners',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('file_path_pc', sa.Text(), nullable=False),
    sa.Column('file_path_sp', sa.Text(), nullable=True),
    sa.Column('alt_text', sa.Text(), nullable=True),
    sa.Column('link_url', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('home_banners')
    # ### end Alembic commands ###
